#!/bin/bash

curl -O -k https://vbinds.ch/sites/default/files/Artifacts/sgf-0.10a.tgz &&
tar xf sgf-0.10a.tgz &&
rm sgf-0.10a.tgz &&
cd sgf &&
mkdir bin &&
cd bin &&
cmake ../source &&
make &&
cd ../../

# rm README.md apt.txt runtime.txt install.R requirements.txt postBuild