name: Build QUiPP pipeline docker images
on: [push]
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAC }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./env-configuration
          file: ./dockerfiles/python3.8-R4.0.4.Dockerfile
          push: true
          tags: oscartgiles/quipp:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}