name: Test pipeline

on: [pull_request]

jobs:
  run_script:

    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v1
      name: checkout

    - 
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAC }}
    - 
      name: Pull and run quipp-pipeline
      run: docker pull oscartgiles/quipp:latest 
    -
      name: Run pipeline
      run: docker run -v $(pwd):/home/jovyan/ oscartgiles/quipp:latest  make
