name: Test pipeline

on: [pull_request]

jobs:
  run_script:

    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v1
      name: checkout
    - 
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAC }}
    -
      name: Run pipeline with privbayes-adult
  
      run: docker run -it -v $GITHUB_WORKSPACE:/quipp-pipeline --workdir /quipp-pipeline turinginst/quipp-env:base make run-privbayes-adult
