name: Test pipeline

on: [pull_request]

jobs:
  run_script:

    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v1
      name: checkout
    - 
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAC }}
    - 
      name: Build pipeline
      run: docker build -f dockerfiles/quipp-dev.Dockerfile -t turinginst/quipp-env:latest .
    -
      name: Run pipeline
      env: 
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: docker run -e KAGGLE_USERNAME=$KAGGLE_USERNAME -e KAGGLE_KEY=$KAGGLE_KEY turinginst/quipp-env:latest make
