# Run simpop R script (including installing dependencies)
name: simpop CI

on:
  push:
    paths:
      - 'methods/simPop/**'
      - '.github/workflows/simpop_ci.yml'

jobs:
  run_script:

    runs-on: ubuntu-18.04
    container:
      image: rocker/tidyverse:3.6.1

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: Rscript -e "install.packages(c('testthat', 'simPop', 'dplyr', 'tidyr', 'magrittr'))"
    - name: Run tests
      run: |-
        cd methods/simPop/
        Rscript -e 'testthat::test_dir("tests", reporter=c("tap", "summary", "fail"))'
